group = one.tranic.sewlia
version = 1.21.4-R0.1-SNAPSHOT

foliaCommit = 6265eb60e755171f5c35accf9bad6b7955eb9c7c

org.gradle.configuration-cache=true
org.gradle.caching = true
org.gradle.parallel = true
org.gradle.vfs.watch = false
org.gradle.jvmargs = -Xmx3G

mcVersion = 1.21.4
GroupMCV = 1.21
preVersion = false
