group = one.tranic.sewlia
version = 1.21.4-R0.1-SNAPSHOT

foliaCommit = 29867414449cede8010bac42dc9bf31dd21eb278

org.gradle.configuration-cache=true
org.gradle.caching = true
org.gradle.parallel = true
org.gradle.vfs.watch = false
org.gradle.jvmargs = -Xmx3G

mcVersion = 1.21.4
GroupMCV = 1.21
preVersion = false
