name: Sewlia Server - dev/1.21.4

on:
  push:
    branches: [ "**" ]
  pull_request:

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest
    environment: default
    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v4
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: 8.12.1
      - name: Setup Powershell
        run: |
          sudo apt-get update
          sudo apt-get install -y wget apt-transport-https software-properties-common
          source /etc/os-release
          wget -q https://packages.microsoft.com/config/ubuntu/$VERSION_ID/packages-microsoft-prod.deb
          sudo dpkg -i packages-microsoft-prod.deb
          rm packages-microsoft-prod.deb
          sudo apt-get update
          sudo apt-get install -y powershell
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'
      - name: Configure Git User Details
        run: git config --global user.email "no-reply@tranic.one" && git config --global user.name "TranicDev"
      - name: Apply Patches
        run: pwsh patch.ps1
      - name: CreateJar
        run: gradle createMojmapPaperclipJar
      - name: SetENV
        run: ./scripts/SetEnv.ps1
      - name: Clear Build
        run: ./scripts/clear_build.ps1
      - name: Upload to Mars API
        run: ./scripts/create_build.ps1 ${{ env.mcversion }} ${{ secrets.MARS_TOKEN }}
      - name: Upload Artifact
        uses: "actions/upload-artifact@v4"
        with:
          name: "${{ env.project_id_b }} CI Artifacts"
          path: "build/libs/*.jar"
      - name: Create Release
        if: "!contains(github.event.commits[0].message, '[release skip]')"
        uses: ncipollo/release-action@v1.14.0
        with:
          tag: ${{ env.tag }}
          name: ${{ env.project_id_b }} ${{ env.mcversion }} - ${{ env.commit_id }}
          body: |
            📦Version: `${{ env.mcversion }}` | Commit ${{ env.commit_id }} [![download](https://img.shields.io/github/downloads/LevelTranic/${{ env.project_id }}/${{ env.tag }}/total?color=red&style=flat-square)](https://github.com/LevelTranic/${{ env.project_id }}/download/${{ env.tag }}/${{ env.jar }})
            This release is automatically compiled by GitHub Actions 
            **You can easily find the latest version in our [build list](https://tranic.one/downloads/all).**
            ### Commit Message
            ${{ env.commit_msg }}
          artifacts: |
            ${{ env.jar_dir }}
          generateReleaseNotes: true
          prerelease: ${{ env.pre }}
          makeLatest: ${{ env.make_latest }}
          token: "${{ secrets.GITHUB_TOKEN }}"